###
### POST request
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "groot with kafka event",
  "email" : "test_event_groot@marvel.com",
  "address" : "Nowhere",
  "dateOfBirth" : "2000-05-15",
  "registeredDate" : "2013-10-10"
}