###
### PUT request to example server
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174003
Content-Type: application/json

{
    "name": "Robert Downer",
    "address": "Stark Tower",
    "dateOfBirth": "1972-06-15"
}
